//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_details
    {
        public int Id { get; set; }
        public int customerId { get; set; }
        public string Address { get; set; }
        public string Pincode { get; set; }
        public string Phonenumber { get; set; }
    }
}
